CREATE TABLE SANPHAM (
  MaSP VARCHAR(20) PRIMARY KEY,
  TenSP NVARCHAR(100) NOT NULL,
  SoLuongTon INT NOT NULL,
  Gia DECIMAL(10,2) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE KHACHHANG (
  MaKH VARCHAR(20) PRIMARY KEY,
  TenKH NVARCHAR(100) NOT NULL,
  TongTienDaChi DECIMAL(12,2) DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE NHANVIEN (
  MaNV VARCHAR(20) PRIMARY KEY,
  TenNV NVARCHAR(100) NOT NULL,
  Luong DECIMAL(12,2) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE HOADON (
  MaHD VARCHAR(20) PRIMARY KEY,
  MaKH VARCHAR(20) NOT NULL,
  MaNV VARCHAR(20) NOT NULL,
  NgayLapHD DATETIME DEFAULT CURRENT_TIMESTAMP,
  TongTienHD DECIMAL(12,2) DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_hd_kh FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
  CONSTRAINT fk_hd_nv FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE CHITIETHOADON (
  MaHD VARCHAR(20),
  MaSP VARCHAR(20),
  SoLuongMua INT NOT NULL,
  DonGiaBan DECIMAL(10,2) NOT NULL,
  ThanhTien DECIMAL(12,2) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (MaHD, MaSP),
  CONSTRAINT fk_cthd_hd FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD),
  CONSTRAINT fk_cthd_sp FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

-- Bảng phân loại sản phẩm (đa hình)
CREATE TABLE DOUONG (
  MaSP VARCHAR(20) PRIMARY KEY,
  DungTich DECIMAL(10,2) NOT NULL,
  CONSTRAINT fk_du_sp FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

CREATE TABLE DOGIADUNG (
  MaSP VARCHAR(20) PRIMARY KEY,
  ChatLieu NVARCHAR(50) NOT NULL,
  CONSTRAINT fk_dgd_sp FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

-- Tạo index bổ sung
CREATE INDEX idx_chitiethoadon_sp ON CHITIETHOADON(MaSP);
CREATE INDEX idx_hoadon_kh ON HOADON(MaKH);
CREATE INDEX idx_hoadon_nv ON HOADON(MaNV);
CREATE TABLE TaiKhoan (
    Username VARCHAR(50) PRIMARY KEY,
    PasswordHash VARCHAR(255) NOT NULL
);

CREATE TABLE TaiKhoanLienKet (
    Username VARCHAR(50),
    LoaiLienKet ENUM('NhanVien','KhachHang') NOT NULL,
    MaNguoi VARCHAR(20) NOT NULL,
    PRIMARY KEY (Username, LoaiLienKet, MaNguoi),
    FOREIGN KEY (Username) REFERENCES TaiKhoan(Username)
    -- Không thể dùng foreign key conditional MySQL, kiểm tra loại & tồn tại ở ứng dụng
);
